name: Keep Streamlit Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Streamlit
        run: curl -L https://medi-assist-ai-rag-v2.streamlit.app